# Generated by Django 4.2.7 on 2023-11-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_historicalreservation_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreservation',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
    ]
