# Generated by Django 4.2.2 on 2023-06-18 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menu_items', to='restaurants.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menus',
            field=models.ManyToManyField(related_name='menu_items', to='restaurants.menu'),
        ),
        migrations.AddField(
            model_name='table',
            name='reservations',
            field=models.ManyToManyField(through='restaurants.Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
