# Generated by Django 4.2.2 on 2023-06-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_menuitem_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Контактный номер')),
            ],
        ),
    ]
