# Generated by Django 4.2.2 on 2023-06-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_staff_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тэг')),
            ],
            options={
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Резервации'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name_plural': 'Столики'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(to='restaurants.tag', verbose_name='Теги'),
        ),
    ]
